name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # 하나의 테스트가 실패해도 다른 테스트는 계속 진행
      matrix:
        python-version: [3.8, 3.9, '3.10']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
        # 설치된 패키지 목록 출력 (디버깅용)
        pip list
    
    - name: Setup test environment
      run: |
        # 환경 변수 설정
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        export TF_CPP_MIN_LOG_LEVEL=2  # TensorFlow 경고 메시지 억제
        
        # 테스트 데이터 디렉토리가 존재하는지 확인
        mkdir -p data
    
    - name: Test with pytest
      run: |
        # -v 플래그로 테스트 실행 과정 자세히 출력
        python -m pytest tests/ --cov=./ --cov-report=xml -v
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
